using System.Text;
using Aigamo.MatchGenerator.Extensions;
using Aigamo.MatchGenerator.Models;

namespace Aigamo.MatchGenerator.Generators;

internal static class EnumCodeGenerator
{
	public static string Generate(EnumMatchModel model)
	{
		var sb = new StringBuilder();

		sb.AppendLineLF("// <auto-generated />");

		sb.AppendLineLF("using System;");
		sb.AppendLineLF("using System.Diagnostics;");

		if (model.Namespace is not null)
		{
			sb.AppendLineLF();
			sb.AppendLineLF($"namespace {model.Namespace};");
		}

		sb.AppendLineLF();
		sb.AppendLineLF($"{model.Accessibility} static class {model.Name}{Constants.MatchExtensionClassSuffix}");
		sb.AppendLineLF("{");
		sb.AppendLineLF("\tpublic static U Match<U>(");
		sb.AppendLineLF($"\t\tthis {model.Name} value,");

		sb.AppendLineLF(string.Join(",\n", model.Members.Select(x => $"\t\tFunc<U> on{x}")));

		sb.AppendLineLF("\t)");
		sb.AppendLineLF("\t{");
		sb.AppendLineLF("\t\treturn value switch");
		sb.AppendLineLF("\t\t{");

		foreach (var member in model.Members)
		{
			sb.AppendLineLF($"\t\t\t{model.Name}.{member} => on{member}(),");
		}

		sb.AppendLineLF("\t\t\t_ => throw new UnreachableException(),");
		sb.AppendLineLF("\t\t};");
		sb.AppendLineLF("\t}");
		sb.AppendLineLF("}");

		return sb.ToString();
	}
}
