using System.Text;
using Aigamo.MatchGenerator.Extensions;
using Aigamo.MatchGenerator.Models;

namespace Aigamo.MatchGenerator.Generators;

internal static class UnionCodeGenerator
{
	private static void GenerateMatchMethod(StringBuilder sb, UnionMatchModel model)
	{
		sb.AppendLineLF($"\tpublic static U Match<U>(");
		sb.AppendLineLF($"\t\tthis {model.Name} value,");

		sb.AppendLineLF(string.Join(",\n", model.DerivedTypes.Select(x => $"\t\tFunc<{x}, U> on{x}")));

		sb.AppendLineLF("\t)");
		sb.AppendLineLF("\t{");
		sb.AppendLineLF("\t\treturn value switch");
		sb.AppendLineLF("\t\t{");

		foreach (var d in model.DerivedTypes)
		{
			sb.AppendLineLF($"\t\t\t{d} x => on{d}(x),");
		}

		sb.AppendLineLF("\t\t\t_ => throw new UnreachableException(),");
		sb.AppendLineLF("\t\t};");
		sb.AppendLineLF("\t}");
	}

	public static string Generate(UnionMatchModel model)
	{
		var sb = new StringBuilder();

		sb.AppendLineLF("// <auto-generated />");

		sb.AppendLineLF("using System;");
		sb.AppendLineLF("using System.Diagnostics;");

		if (model.Namespace is not null)
		{
			sb.AppendLineLF();
			sb.AppendLineLF($"namespace {model.Namespace};");
		}

		sb.AppendLineLF();
		sb.AppendLineLF($"{model.Accessibility} static class {model.Name}{Constants.MatchExtensionClassSuffix}");
		sb.AppendLineLF("{");

		GenerateMatchMethod(sb, model);

		sb.AppendLineLF("}");

		return sb.ToString();
	}
}
