using System.Text;
using Aigamo.MatchGenerator.Extensions;
using Aigamo.MatchGenerator.Models;

namespace Aigamo.MatchGenerator.Generators;

internal static class UnionCodeGenerator
{
	private static void GenerateMatchMethod(StringBuilder sb, MatchModel.Union model)
	{
		sb.AppendLineLF("\t[MethodImpl(MethodImplOptions.AggressiveInlining)]");
		sb.AppendLineLF(
			$"\tpublic static U Match<{model.TypeParameters.ToMethodTypeParameterPrefix()}U>("
		);
		sb.AppendLineLF($"\t\tthis {model.TypeName} value,");

		sb.AppendLineLF(
			string.Join(
				",\n",
				model.DerivedTypes.Select(x => $"\t\tFunc<{x.TypeName}, U> on{x.Name}")
			)
		);

		sb.AppendLineLF("\t)");
		sb.AppendLineLF("\t{");
		sb.AppendLineLF("\t\treturn value switch");
		sb.AppendLineLF("\t\t{");

		foreach (var d in model.DerivedTypes)
		{
			sb.AppendLineLF($"\t\t\t{d.TypeName} x => on{d.Name}(x),");
		}

		sb.AppendLineLF("\t\t\t_ => throw new UnreachableException(),");
		sb.AppendLineLF("\t\t};");
		sb.AppendLineLF("\t}");
	}

	private static void GenerateMatchAsyncMethod(StringBuilder sb, MatchModel.Union model)
	{
		sb.AppendLineLF(
			$"\tpublic static async Task<U> Match<{model.TypeParameters.ToMethodTypeParameterPrefix()}U>("
		);
		sb.AppendLineLF($"\t\tthis Task<{model.TypeName}> value,");

		sb.AppendLineLF(
			string.Join(
				",\n",
				model.DerivedTypes.Select(x => $"\t\tFunc<{x.TypeName}, U> on{x.Name}")
			)
		);

		sb.AppendLineLF("\t)");
		sb.AppendLineLF("\t{");
		sb.AppendLineLF("\t\treturn (await value.ConfigureAwait(false)) switch");
		sb.AppendLineLF("\t\t{");

		foreach (var d in model.DerivedTypes)
		{
			sb.AppendLineLF($"\t\t\t{d.TypeName} x => on{d.Name}(x),");
		}

		sb.AppendLineLF("\t\t\t_ => throw new UnreachableException(),");
		sb.AppendLineLF("\t\t};");
		sb.AppendLineLF("\t}");
	}

	public static string Generate(MatchModel.Union model)
	{
		var sb = new StringBuilder();

		sb.AppendLineLF("// <auto-generated />");

		sb.AppendLineLF("using System;");
		sb.AppendLineLF("using System.Diagnostics;");
		sb.AppendLineLF("using System.Runtime.CompilerServices;");
		sb.AppendLineLF("using System.Threading.Tasks;");

		if (model.Namespace is not null)
		{
			sb.AppendLineLF();
			sb.AppendLineLF($"namespace {model.Namespace};");
		}

		sb.AppendLineLF();
		sb.AppendLineLF(
			$"{model.Accessibility} static class {model.Name}{Constants.MatchExtensionClassSuffix}"
		);
		sb.AppendLineLF("{");

		GenerateMatchMethod(sb, model);
		sb.AppendLineLF();
		GenerateMatchAsyncMethod(sb, model);

		sb.AppendLineLF("}");

		return sb.ToString();
	}
}
