using System.Collections.Immutable;
using System.Diagnostics;
using System.Text;
using Aigamo.MatchGenerator.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Aigamo.MatchGenerator;

static file class AccessibilityMatchExtensions
{
	public static U Match<U>(
		this Accessibility value,
		Func<U> onNotApplicable,
		Func<U> onPrivate,
		Func<U> onProtectedAndInternal,
		Func<U> onProtected,
		Func<U> onInternal,
		Func<U> onProtectedOrInternal,
		Func<U> onPublic
	)
	{
		return value switch
		{
			Accessibility.NotApplicable => onNotApplicable(),
			Accessibility.Private => onPrivate(),
			Accessibility.ProtectedAndInternal => onProtectedAndInternal(),
			Accessibility.Protected => onProtected(),
			Accessibility.Internal => onInternal(),
			Accessibility.ProtectedOrInternal => onProtectedOrInternal(),
			Accessibility.Public => onPublic(),
			_ => throw new UnreachableException(),
		};
	}
}

[Generator]
internal class SourceGenerator : IIncrementalGenerator
{
	private static Accessibility Min(Accessibility left, Accessibility right)
	{
		return (Accessibility)Math.Min((int)left, (int)right);
	}

	private static string ToCode(Accessibility accessibility)
	{
		return accessibility.Match(
			onNotApplicable: () => "internal",
			onPrivate: () => "private",
			onProtectedAndInternal: () => "private protected",
			onProtected: () => "protected",
			onInternal: () => "internal",
			onProtectedOrInternal: () => "protected internal",
			onPublic: () => "public"
		);
	}

	private static string GetEffectiveAccessibility(INamedTypeSymbol symbol)
	{
		var accessibility = symbol.DeclaredAccessibility;

		var current = symbol.ContainingType;
		while (current is not null)
		{
			accessibility = Min(accessibility, current.DeclaredAccessibility);
			current = current.ContainingType;
		}

		return ToCode(accessibility);
	}

	private static void GenerateForEnum(INamedTypeSymbol enumType, SourceProductionContext context)
	{
		var members = enumType.GetMembers()
			.OfType<IFieldSymbol>()
			.Where(x => x.ConstantValue is not null)
			.OrderBy(x => x.Name)
			.ToList();

		if (members is { Count: 0 })
		{
			return;
		}

		var enumName = enumType.Name;
		var namespaceName = enumType.ContainingNamespace.IsGlobalNamespace
			? null
			: enumType.ContainingNamespace.ToDisplayString();

		var accessibility = GetEffectiveAccessibility(enumType);

		var sb = new StringBuilder();

		sb.AppendLineLF("// <auto-generated />");

		sb.AppendLineLF("using System;");
		sb.AppendLineLF("using System.Diagnostics;");

		if (namespaceName is not null)
		{
			sb.AppendLineLF();
			sb.AppendLineLF($"namespace {namespaceName};");
		}

		sb.AppendLineLF();
		sb.AppendLineLF($"{accessibility} static class {enumName}{Constants.MatchExtensionClassSuffix}");
		sb.AppendLineLF("{");
		sb.AppendLineLF("\tpublic static U Match<U>(");
		sb.AppendLineLF($"\t\tthis {enumName} value,");

		sb.AppendLineLF(string.Join(",\n", members.Select(x => $"\t\tFunc<U> on{x.Name}")));

		sb.AppendLineLF("\t)");
		sb.AppendLineLF("\t{");
		sb.AppendLineLF("\t\treturn value switch");
		sb.AppendLineLF("\t\t{");

		foreach (var member in members)
		{
			sb.AppendLineLF($"\t\t\t{enumName}.{member.Name} => on{member.Name}(),");
		}

		sb.AppendLineLF("\t\t\t_ => throw new UnreachableException(),");
		sb.AppendLineLF("\t\t};");
		sb.AppendLineLF("\t}");
		sb.AppendLineLF("}");

		context.AddSource($"{enumName}{Constants.MatchExtensionClassSuffix}.g.cs", sb.ToString());
	}

	private static bool IsDerivedFrom(INamedTypeSymbol type, INamedTypeSymbol baseType)
	{
		while (type.BaseType is not null)
		{
			if (SymbolEqualityComparer.Default.Equals(type.BaseType, baseType))
				return true;

			type = type.BaseType;
		}
		return false;
	}

	private static IEnumerable<INamedTypeSymbol> GetDerivedTypes(
		INamedTypeSymbol baseType,
		Compilation compilation
	)
	{
		foreach (var tree in compilation.SyntaxTrees)
		{
			var model = compilation.GetSemanticModel(tree);

			var types = tree.GetRoot()
				.DescendantNodes()
				.OfType<TypeDeclarationSyntax>();

			foreach (var t in types)
			{
				if (model.GetDeclaredSymbol(t) is INamedTypeSymbol symbol)
				{
					if (IsDerivedFrom(symbol, baseType))
						yield return symbol;
				}
			}
		}
	}

	private static void GenerateMatchMethod(
		StringBuilder sb,
		string baseName,
		List<INamedTypeSymbol> derived
	)
	{
		sb.AppendLineLF($"\tpublic static U Match<U>(");
		sb.AppendLineLF($"\t\tthis {baseName} value,");

		sb.AppendLineLF(string.Join(",\n", derived.Select(x => $"\t\tFunc<{x.Name}, U> on{x.Name}")));

		sb.AppendLineLF("\t)");
		sb.AppendLineLF("\t{");
		sb.AppendLineLF("\t\treturn value switch");
		sb.AppendLineLF("\t\t{");

		foreach (var d in derived)
		{
			sb.AppendLineLF($"\t\t\t{d.Name} x => {ToParam(d.Name)}(x),");
		}

		sb.AppendLineLF("\t\t\t_ => throw new UnreachableException(),");
		sb.AppendLineLF("\t\t};");
		sb.AppendLineLF("\t}");
	}

	private static string ToParam(string typeName)
	{
		return $"on{typeName}";
	}

	private static void GenerateForUnion(
		INamedTypeSymbol baseType,
		Compilation compilation,
		SourceProductionContext context
	)
	{
		if (!baseType.IsAbstract)
			return;

		var derived = GetDerivedTypes(baseType, compilation)
			.Where(x => !x.IsAbstract)
			.OrderBy(x => x.Name)
			.ToList();

		if (derived.Count == 0)
			return;

		var baseName = baseType.Name;
		var namespaceName = baseType.ContainingNamespace.IsGlobalNamespace
			? null
			: baseType.ContainingNamespace.ToDisplayString();

		var sb = new StringBuilder();

		sb.AppendLineLF("// <auto-generated />");

		sb.AppendLineLF("using System;");
		sb.AppendLineLF("using System.Diagnostics;");

		if (namespaceName is not null)
		{
			sb.AppendLineLF();
			sb.AppendLineLF($"namespace {namespaceName};");
		}

		sb.AppendLineLF();
		sb.AppendLineLF($"{GetEffectiveAccessibility(baseType)} static class {baseName}{Constants.MatchExtensionClassSuffix}");
		sb.AppendLineLF("{");

		GenerateMatchMethod(sb, baseName, derived);

		sb.AppendLineLF("}");

		context.AddSource($"{baseName}{Constants.MatchExtensionClassSuffix}.g.cs", sb.ToString());
	}

	private static void Execute(
		Compilation compilation,
		ImmutableArray<INamedTypeSymbol> targets,
		SourceProductionContext context
	)
	{
		foreach (INamedTypeSymbol type in targets.Distinct(SymbolEqualityComparer.Default))
		{
			if (type.TypeKind == TypeKind.Enum)
			{
				GenerateForEnum(type, context);
			}
			else
			{
				GenerateForUnion(type, compilation, context);
			}
		}
	}

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(ctx =>
		{
			ctx.AddSource("GenerateMatchAttribute.g.cs", """
				using System;

				namespace Aigamo.MatchGenerator;

				[AttributeUsage(AttributeTargets.Class | AttributeTargets.Enum)]
				internal sealed class GenerateMatchAttribute : Attribute;
				""");
		});

		var targets = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				"Aigamo.MatchGenerator.GenerateMatchAttribute",
				static (node, _) => node is TypeDeclarationSyntax or EnumDeclarationSyntax,
				static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol
			);

		var compilationAndTargets = context.CompilationProvider.Combine(targets.Collect());

		context.RegisterSourceOutput(compilationAndTargets, static (spc, source) => Execute(source.Left, source.Right, spc));
	}
}
