using System.Text;
using Aigamo.MatchGenerator.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Aigamo.MatchGenerator;

static file class AccessibilityMatchExtensions
{
	public static U Match<U>(
		this Accessibility value,
		Func<U> onNotApplicable,
		Func<U> onPrivate,
		Func<U> onProtectedAndInternal,
		Func<U> onProtected,
		Func<U> onInternal,
		Func<U> onProtectedOrInternal,
		Func<U> onPublic
	)
	{
		return value switch
		{
			Accessibility.NotApplicable => onNotApplicable(),
			Accessibility.Private => onPrivate(),
			Accessibility.ProtectedAndInternal => onProtectedAndInternal(),
			Accessibility.Protected => onProtected(),
			Accessibility.Internal => onInternal(),
			Accessibility.ProtectedOrInternal => onProtectedOrInternal(),
			Accessibility.Public => onPublic(),
			_ => throw new System.Diagnostics.UnreachableException(),
		};
	}
}

[Generator]
internal class SourceGenerator : IIncrementalGenerator
{
	private static INamedTypeSymbol? GetEnumSymbol(GeneratorSyntaxContext context)
	{
		var enumSyntax = (EnumDeclarationSyntax)context.Node;
		var symbol = context.SemanticModel.GetDeclaredSymbol(enumSyntax);
		return symbol as INamedTypeSymbol;
	}

	private static Accessibility Min(Accessibility left, Accessibility right)
	{
		return (Accessibility)Math.Min((int)left, (int)right);
	}

	private static string ToCode(Accessibility accessibility)
	{
		return accessibility.Match(
			onNotApplicable: () => "internal",
			onPrivate: () => "private",
			onProtectedAndInternal: () => "private protected",
			onProtected: () => "protected",
			onInternal: () => "internal",
			onProtectedOrInternal: () => "protected internal",
			onPublic: () => "public"
		);
	}

	private static string GetEffectiveAccessibility(INamedTypeSymbol symbol)
	{
		var accessibility = symbol.DeclaredAccessibility;

		var current = symbol.ContainingType;
		while (current is not null)
		{
			accessibility = Min(accessibility, current.DeclaredAccessibility);
			current = current.ContainingType;
		}

		return ToCode(accessibility);
	}

	private static void Generate(SourceProductionContext context, INamedTypeSymbol enumSymbol)
	{
		var members = enumSymbol.GetMembers()
			.OfType<IFieldSymbol>()
			.Where(x => x.ConstantValue is not null)
			.ToList();

		if (members is { Count: 0 })
		{
			return;
		}

		var enumName = enumSymbol.Name;
		var namespaceName = enumSymbol.ContainingNamespace.IsGlobalNamespace
			? null
			: enumSymbol.ContainingNamespace.ToDisplayString();

		var accessibility = GetEffectiveAccessibility(enumSymbol);

		var sb = new StringBuilder();

		sb.AppendLineLF("// <auto-generated />");

		if (namespaceName is not null)
		{
			sb.AppendLineLF($"namespace {namespaceName};");
			sb.AppendLineLF();
		}

		sb.AppendLineLF($"{accessibility} static class {enumName}{Constants.ExtensionClassSuffix}");
		sb.AppendLineLF("{");
		sb.AppendLineLF("\tpublic static U Match<U>(");
		sb.AppendLineLF($"\t\tthis {enumName} value,");

		sb.AppendLineLF(string.Join(",\n", members.Select(x => $"\t\tFunc<U> on{x.Name}")));

		sb.AppendLineLF("\t)");
		sb.AppendLineLF("\t{");
		sb.AppendLineLF("\t\treturn value switch");
		sb.AppendLineLF("\t\t{");

		foreach (var member in members)
		{
			sb.AppendLineLF($"\t\t\t{enumName}.{member.Name} => on{member.Name}(),");
		}

		sb.AppendLineLF("\t\t\t_ => throw new System.Diagnostics.UnreachableException(),");
		sb.AppendLineLF("\t\t};");
		sb.AppendLineLF("\t}");
		sb.AppendLineLF("}");

		context.AddSource($"{enumName}{Constants.ExtensionClassSuffix}.g.cs", sb.ToString());
	}

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var enums = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (node, _) => node is EnumDeclarationSyntax,
				transform: static (ctx, _) => GetEnumSymbol(ctx)
			)
			.WhereNotNull();

		context.RegisterSourceOutput(enums, static (spc, enumSymbol) =>
		{
			Generate(spc, enumSymbol);
		});
	}
}
