using System.Text;
using Aigamo.MatchGenerator.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Aigamo.MatchGenerator;

[Generator]
internal class SourceGenerator : IIncrementalGenerator
{
	private static INamedTypeSymbol? GetEnumSymbol(GeneratorSyntaxContext context)
	{
		var enumSyntax = (EnumDeclarationSyntax)context.Node;
		var symbol = context.SemanticModel.GetDeclaredSymbol(enumSyntax);
		return symbol as INamedTypeSymbol;
	}

	private static void Generate(SourceProductionContext context, INamedTypeSymbol enumSymbol)
	{
		var members = enumSymbol.GetMembers()
			.OfType<IFieldSymbol>()
			.Where(x => x.ConstantValue is not null)
			.ToList();

		if (members is { Count: 0 })
		{
			return;
		}

		var enumName = enumSymbol.Name;
		var namespaceName = enumSymbol.ContainingNamespace.IsGlobalNamespace
			? null
			: enumSymbol.ContainingNamespace.ToDisplayString();

		var sb = new StringBuilder();

		sb.AppendLineLF("// <auto-generated />");

		if (namespaceName is not null)
		{
			sb.AppendLineLF($"namespace {namespaceName};");
			sb.AppendLineLF();
		}

		sb.AppendLineLF($"internal static class {enumName}{Constants.ExtensionClassSuffix}");
		sb.AppendLineLF("{");
		sb.AppendLineLF("\tpublic static U Match<U>(");
		sb.AppendLineLF($"\t\tthis {enumName} value,");

		sb.AppendLineLF(string.Join(",\n", members.Select(x => $"\t\tFunc<U> on{x.Name}")));

		sb.AppendLineLF("\t)");
		sb.AppendLineLF("\t{");
		sb.AppendLineLF("\t\treturn value switch");
		sb.AppendLineLF("\t\t{");

		foreach (var member in members)
		{
			sb.AppendLineLF($"\t\t\t{enumName}.{member.Name} => on{member.Name}(),");
		}

		sb.AppendLineLF("\t\t\t_ => throw new System.Diagnostics.UnreachableException(),");
		sb.AppendLineLF("\t\t};");
		sb.AppendLineLF("\t}");
		sb.AppendLineLF("}");

		context.AddSource($"{enumName}{Constants.ExtensionClassSuffix}.g.cs", sb.ToString());
	}

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var enums = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (node, _) => node is EnumDeclarationSyntax,
				transform: static (ctx, _) => GetEnumSymbol(ctx)
			)
			.WhereNotNull();

		context.RegisterSourceOutput(enums, static (spc, enumSymbol) =>
		{
			Generate(spc, enumSymbol);
		});
	}
}
