using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Aigamo.MatchGenerator.Tests;

public class EnumMatchGeneratorTests
{
	private static GeneratorDriverRunResult Run(string source)
	{
		var syntaxTree = CSharpSyntaxTree.ParseText(source);

		var compilation = CSharpCompilation.Create(
			"Tests",
			[syntaxTree],
			[
				MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
				MetadataReference.CreateFromFile(typeof(Func<>).Assembly.Location),
			],
			new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
		);

		var generator = new SourceGenerator();

		GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
		driver = driver.RunGenerators(compilation);

		return driver.GetRunResult();
	}

	private static string RunGenerator(string source)
	{
		var result = Run(source);
		return result.GeneratedTrees[1].GetText().ToString();
	}

	private static List<string> RunGeneratorAll(string source)
	{
		var result = Run(source);
		return [.. result.GeneratedTrees.Select(t => t.GetText().ToString())];
	}

	[Fact]
	public void Generates_Match_Method_For_Enum()
	{
		// Arrange
		var source = @"
using Aigamo.MatchGenerator;

namespace Test;

[GenerateMatch]
public enum Gender
{
	Male = 1,
	Female,
}
";

		var actual = RunGenerator(source);

		var expected = """
			// <auto-generated />
			namespace Test;

			public static class GenderMatchExtensions
			{
				public static U Match<U>(
					this Gender value,
					System.Func<U> onFemale,
					System.Func<U> onMale
				)
				{
					return value switch
					{
						Gender.Female => onFemale(),
						Gender.Male => onMale(),
						_ => throw new System.Diagnostics.UnreachableException(),
					};
				}
			}

			""";

		// Assert
		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Generates_Match_Method_For_Global_Namespace_Enum()
	{
		// Arrange
		var source = @"
using Aigamo.MatchGenerator;

[GenerateMatch]
public enum Gender
{
	Male = 1,
	Female,
}
";

		var actual = RunGenerator(source);

		var expected = """
		// <auto-generated />
		public static class GenderMatchExtensions
		{
			public static U Match<U>(
				this Gender value,
				System.Func<U> onFemale,
				System.Func<U> onMale
			)
			{
				return value switch
				{
					Gender.Female => onFemale(),
					Gender.Male => onMale(),
					_ => throw new System.Diagnostics.UnreachableException(),
				};
			}
		}

		""";

		// Assert
		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Generates_Match_For_Simple_Enum()
	{
		var source = """
		using Aigamo.MatchGenerator;

		namespace Test;

		[GenerateMatch]
		public enum Gender
		{
			Male = 1,
			Female
		}
		""";

		var actual = RunGenerator(source);

		var expected = """
		// <auto-generated />
		namespace Test;

		public static class GenderMatchExtensions
		{
			public static U Match<U>(
				this Gender value,
				System.Func<U> onFemale,
				System.Func<U> onMale
			)
			{
				return value switch
				{
					Gender.Female => onFemale(),
					Gender.Male => onMale(),
					_ => throw new System.Diagnostics.UnreachableException(),
				};
			}
		}

		""";

		// Assert
		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Matches_Internal_Accessibility()
	{
		var source = """
		using Aigamo.MatchGenerator;

		namespace Test;

		[GenerateMatch]
		internal enum Gender
		{
			Male,
			Female
		}
		""";

		var actual = RunGenerator(source);

		var expected = """
		// <auto-generated />
		namespace Test;

		internal static class GenderMatchExtensions
		{
			public static U Match<U>(
				this Gender value,
				System.Func<U> onFemale,
				System.Func<U> onMale
			)
			{
				return value switch
				{
					Gender.Female => onFemale(),
					Gender.Male => onMale(),
					_ => throw new System.Diagnostics.UnreachableException(),
				};
			}
		}

		""";

		// Assert
		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Respects_Containing_Type_Accessibility()
	{
		var source = """
		using Aigamo.MatchGenerator;

		namespace Test;

		internal class Container
		{
			[GenerateMatch]
			public enum Gender
			{
				Male,
				Female
			}
		}
		""";

		var actual = RunGenerator(source);

		var expected = """
		// <auto-generated />
		namespace Test;

		internal static class GenderMatchExtensions
		{
			public static U Match<U>(
				this Gender value,
				System.Func<U> onFemale,
				System.Func<U> onMale
			)
			{
				return value switch
				{
					Gender.Female => onFemale(),
					Gender.Male => onMale(),
					_ => throw new System.Diagnostics.UnreachableException(),
				};
			}
		}

		""";

		// Assert
		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Generates_For_Multiple_Enums()
	{
		var source = """
		using Aigamo.MatchGenerator;

		namespace Test;

		[GenerateMatch]
		public enum A { X, Y }
		[GenerateMatch]
		public enum B { P, Q }
		""";

		var result = RunGeneratorAll(source);

		Assert.Contains(result, x => x.Contains("AMatchExtensions"));
		Assert.Contains(result, x => x.Contains("BMatchExtensions"));
	}

	[Fact]
	public void Generates_Match_Method_For_Record_Hierarchy()
	{
		var source = """
	using Aigamo.MatchGenerator;

	namespace Test;

	[GenerateMatch]
	abstract record MaritalStatus;

	sealed record Single : MaritalStatus;
	sealed record Married : MaritalStatus;
	sealed record Divorced : MaritalStatus;
	sealed record Widowed : MaritalStatus;
	""";

		var actual = RunGenerator(source);

		var expected = """
	// <auto-generated />
	namespace Test;

	internal static class MaritalStatusMatchExtensions
	{
		public static U Match<U>(
			this MaritalStatus value,
			System.Func<Divorced, U> onDivorced,
			System.Func<Married, U> onMarried,
			System.Func<Single, U> onSingle,
			System.Func<Widowed, U> onWidowed
		)
		{
			return value switch
			{
				Divorced x => onDivorced(x),
				Married x => onMarried(x),
				Single x => onSingle(x),
				Widowed x => onWidowed(x),
				_ => throw new System.Diagnostics.UnreachableException(),
			};
		}
	}

	""";

		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Generates_Match_For_Record_Hierarchy_In_Global_Namespace()
	{
		var source = """
	using Aigamo.MatchGenerator;

	[GenerateMatch]
	abstract record MaritalStatus;

	sealed record Single : MaritalStatus;
	sealed record Married : MaritalStatus;
	sealed record Divorced : MaritalStatus;
	sealed record Widowed : MaritalStatus;
	""";

		var actual = RunGenerator(source);

		var expected = """
	// <auto-generated />
	internal static class MaritalStatusMatchExtensions
	{
		public static U Match<U>(
			this MaritalStatus value,
			System.Func<Divorced, U> onDivorced,
			System.Func<Married, U> onMarried,
			System.Func<Single, U> onSingle,
			System.Func<Widowed, U> onWidowed
		)
		{
			return value switch
			{
				Divorced x => onDivorced(x),
				Married x => onMarried(x),
				Single x => onSingle(x),
				Widowed x => onWidowed(x),
				_ => throw new System.Diagnostics.UnreachableException(),
			};
		}
	}

	""";

		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Matches_Record_Accessibility()
	{
		var source = """
	using Aigamo.MatchGenerator;

	namespace Test;

	[GenerateMatch]
	internal abstract record MaritalStatus;

	internal sealed record Single : MaritalStatus;
	internal sealed record Married : MaritalStatus;
	internal sealed record Divorced : MaritalStatus;
	internal sealed record Widowed : MaritalStatus;
	""";

		var actual = RunGenerator(source);

		var expected = """
	// <auto-generated />
	namespace Test;

	internal static class MaritalStatusMatchExtensions
	{
		public static U Match<U>(
			this MaritalStatus value,
			System.Func<Divorced, U> onDivorced,
			System.Func<Married, U> onMarried,
			System.Func<Single, U> onSingle,
			System.Func<Widowed, U> onWidowed
		)
		{
			return value switch
			{
				Divorced x => onDivorced(x),
				Married x => onMarried(x),
				Single x => onSingle(x),
				Widowed x => onWidowed(x),
				_ => throw new System.Diagnostics.UnreachableException(),
			};
		}
	}

	""";

		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Respects_Containing_Type_Accessibility_For_Record_Hierarchy()
	{
		var source = """
	using Aigamo.MatchGenerator;

	namespace Test;

	internal class Container
	{
		[GenerateMatch]
		public abstract record MaritalStatus;

		public sealed record Single : MaritalStatus;
		public sealed record Married : MaritalStatus;
		public sealed record Divorced : MaritalStatus;
		public sealed record Widowed : MaritalStatus;
	}
	""";

		var actual = RunGenerator(source);

		var expected = """
	// <auto-generated />
	namespace Test;

	internal static class MaritalStatusMatchExtensions
	{
		public static U Match<U>(
			this MaritalStatus value,
			System.Func<Divorced, U> onDivorced,
			System.Func<Married, U> onMarried,
			System.Func<Single, U> onSingle,
			System.Func<Widowed, U> onWidowed
		)
		{
			return value switch
			{
				Divorced x => onDivorced(x),
				Married x => onMarried(x),
				Single x => onSingle(x),
				Widowed x => onWidowed(x),
				_ => throw new System.Diagnostics.UnreachableException(),
			};
		}
	}

	""";

		Assert.Equal(expected, actual);
	}
}
