using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Aigamo.MatchGenerator.Tests;

public class EnumMatchGeneratorTests
{
	[Fact]
	public void Generates_Match_Method_For_Enum()
	{
		// Arrange
		var source = @"
namespace Test;

public enum Gender
{
	Male = 1,
	Female,
}
";

		var syntaxTree = CSharpSyntaxTree.ParseText(source);

		var compilation = CSharpCompilation.Create(
			"Tests",
			[syntaxTree],
			[
				MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
				MetadataReference.CreateFromFile(typeof(Enumerable).Assembly.Location),
			],
			new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
		);

		var generator = new SourceGenerator();

		// Act
		GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
		_ = driver.RunGeneratorsAndUpdateCompilation(
			compilation,
			out var outputCompilation,
			out _
		);

		var generatedTrees = outputCompilation.SyntaxTrees
			.Skip(1) // first is original
			.ToList();

		var generatedCode = generatedTrees[0].ToString();

		var expected = """
			// <auto-generated />
			namespace Test;

			internal static class GenderMatchExtensions
			{
				public static U Match<U>(
					this Gender value,
					Func<U> onMale,
					Func<U> onFemale
				)
				{
					return value switch
					{
						Gender.Male => onMale(),
						Gender.Female => onFemale(),
						_ => throw new System.Diagnostics.UnreachableException(),
					};
				}
			}

			""";

		// Assert
		Assert.Equal(expected, generatedCode);
	}
}
