using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Aigamo.MatchGenerator.Tests;

public class EnumMatchGeneratorTests
{
	private sealed class TestAnalyzerConfigOptions(Dictionary<string, string> options)
		: AnalyzerConfigOptions
	{
		public override bool TryGetValue(string key, out string value) =>
			options.TryGetValue(key, out value!);
	}

	// Mirrors a section-scoped .editorconfig entry (e.g. under [*.cs]): visible per-tree,
	// not via GlobalOptions. This is the shape that exposed the real bug — the generator
	// originally only checked GlobalOptions, so a [*.cs]-scoped setting was silently ignored.
	private sealed class TestAnalyzerConfigOptionsProvider(AnalyzerConfigOptions treeOptions)
		: AnalyzerConfigOptionsProvider
	{
		public override AnalyzerConfigOptions GlobalOptions { get; } =
			new TestAnalyzerConfigOptions([]);

		public override AnalyzerConfigOptions GetOptions(SyntaxTree tree) => treeOptions;

		public override AnalyzerConfigOptions GetOptions(AdditionalText textFile) => treeOptions;
	}

	private static GeneratorDriverRunResult Run(string source, string? parameterPrefix = null)
	{
		var syntaxTree = CSharpSyntaxTree.ParseText(source);

		var compilation = CSharpCompilation.Create(
			"Tests",
			[syntaxTree],
			[
				MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
				MetadataReference.CreateFromFile(typeof(Func<>).Assembly.Location),
			],
			new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
		);

		var generator = new SourceGenerator();

		GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
		if (parameterPrefix is not null)
		{
			driver = driver.WithUpdatedAnalyzerConfigOptions(
				new TestAnalyzerConfigOptionsProvider(
					new TestAnalyzerConfigOptions(
						new Dictionary<string, string>
						{
							["matchgenerator_parameter_prefix"] = parameterPrefix,
						}
					)
				)
			);
		}
		driver = driver.RunGenerators(compilation);

		return driver.GetRunResult();
	}

	private static string RunGenerator(string source, string? parameterPrefix = null)
	{
		var result = Run(source, parameterPrefix);
		return result
			.GeneratedTrees.Single(t => t.FilePath.EndsWith("MatchExtensions.g.cs"))
			.GetText()
			.ToString();
	}

	private static List<string> RunGeneratorAll(string source)
	{
		var result = Run(source);
		return [.. result.GeneratedTrees.Select(t => t.GetText().ToString())];
	}

	[Fact]
	public void Generates_Match_Method_For_Enum()
	{
		// Arrange
		var source =
			@"
using Aigamo.MatchGenerator;

namespace Test;

[GenerateMatch]
public enum Gender
{
	Male = 1,
	Female,
}
";

		var actual = RunGenerator(source);

		var expected = """
			// <auto-generated />
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;

			namespace Test;

			public static class GenderMatchExtensions
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static U Match<U>(
					this Gender value,
					Func<U> Male,
					Func<U> Female
				)
				{
					return value switch
					{
						Gender.Male => Male(),
						Gender.Female => Female(),
						_ => throw new UnreachableException(),
					};
				}
			}

			""";

		// Assert
		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Generates_Match_Method_With_Custom_Parameter_Prefix()
	{
		// Arrange
		var source =
			@"
using Aigamo.MatchGenerator;

namespace Test;

[GenerateMatch]
public enum Gender
{
	Male = 1,
	Female,
}
";

		var actual = RunGenerator(source, parameterPrefix: "on");

		var expected = """
			// <auto-generated />
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;

			namespace Test;

			public static class GenderMatchExtensions
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static U Match<U>(
					this Gender value,
					Func<U> onMale,
					Func<U> onFemale
				)
				{
					return value switch
					{
						Gender.Male => onMale(),
						Gender.Female => onFemale(),
						_ => throw new UnreachableException(),
					};
				}
			}

			""";

		// Assert
		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Generates_Match_Method_For_Global_Namespace_Enum()
	{
		// Arrange
		var source =
			@"
using Aigamo.MatchGenerator;

[GenerateMatch]
public enum Gender
{
	Male = 1,
	Female,
}
";

		var actual = RunGenerator(source);

		var expected = """
			// <auto-generated />
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;

			public static class GenderMatchExtensions
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static U Match<U>(
					this Gender value,
					Func<U> Male,
					Func<U> Female
				)
				{
					return value switch
					{
						Gender.Male => Male(),
						Gender.Female => Female(),
						_ => throw new UnreachableException(),
					};
				}
			}

			""";

		// Assert
		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Generates_Match_For_Simple_Enum()
	{
		var source = """
			using Aigamo.MatchGenerator;

			namespace Test;

			[GenerateMatch]
			public enum Gender
			{
				Male = 1,
				Female
			}
			""";

		var actual = RunGenerator(source);

		var expected = """
			// <auto-generated />
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;

			namespace Test;

			public static class GenderMatchExtensions
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static U Match<U>(
					this Gender value,
					Func<U> Male,
					Func<U> Female
				)
				{
					return value switch
					{
						Gender.Male => Male(),
						Gender.Female => Female(),
						_ => throw new UnreachableException(),
					};
				}
			}

			""";

		// Assert
		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Matches_Internal_Accessibility()
	{
		var source = """
			using Aigamo.MatchGenerator;

			namespace Test;

			[GenerateMatch]
			internal enum Gender
			{
				Male,
				Female
			}
			""";

		var actual = RunGenerator(source);

		var expected = """
			// <auto-generated />
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;

			namespace Test;

			internal static class GenderMatchExtensions
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static U Match<U>(
					this Gender value,
					Func<U> Male,
					Func<U> Female
				)
				{
					return value switch
					{
						Gender.Male => Male(),
						Gender.Female => Female(),
						_ => throw new UnreachableException(),
					};
				}
			}

			""";

		// Assert
		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Respects_Containing_Type_Accessibility()
	{
		var source = """
			using Aigamo.MatchGenerator;

			namespace Test;

			internal class Container
			{
				[GenerateMatch]
				public enum Gender
				{
					Male,
					Female
				}
			}
			""";

		var actual = RunGenerator(source);

		var expected = """
			// <auto-generated />
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;

			namespace Test;

			internal static class GenderMatchExtensions
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static U Match<U>(
					this Container.Gender value,
					Func<U> Male,
					Func<U> Female
				)
				{
					return value switch
					{
						Container.Gender.Male => Male(),
						Container.Gender.Female => Female(),
						_ => throw new UnreachableException(),
					};
				}
			}

			""";

		// Assert
		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Generates_For_Multiple_Enums()
	{
		var source = """
			using Aigamo.MatchGenerator;

			namespace Test;

			[GenerateMatch]
			public enum A { X, Y }
			[GenerateMatch]
			public enum B { P, Q }
			""";

		var result = RunGeneratorAll(source);

		Assert.Contains(result, x => x.Contains("AMatchExtensions"));
		Assert.Contains(result, x => x.Contains("BMatchExtensions"));
	}

	[Fact]
	public void Generates_Match_For_External_Type_Via_Assembly_Attribute()
	{
		// Color is not annotated with [GenerateMatch]; it's targeted from outside.
		var source = """
			using Aigamo.MatchGenerator;

			[assembly: GenerateMatchFor(typeof(Test.Color))]

			namespace Test;

			public enum Color
			{
				Red,
				Green,
				Blue
			}
			""";

		var actual = RunGenerator(source);

		// External targets are generated as internal (a local convenience, not public API).
		var expected = """
			// <auto-generated />
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;

			namespace Test;

			internal static class ColorMatchExtensions
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static U Match<U>(
					this Color value,
					Func<U> Red,
					Func<U> Green,
					Func<U> Blue
				)
				{
					return value switch
					{
						Color.Red => Red(),
						Color.Green => Green(),
						Color.Blue => Blue(),
						_ => throw new UnreachableException(),
					};
				}
			}

			""";

		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Collapses_Enum_Members_That_Share_A_Constant_Value()
	{
		// Friend aliases Internal (same constant value), like Roslyn's Accessibility
		// enum. Emitting both would produce duplicate switch case labels (CS8510) and
		// duplicate parameters, so aliased members collapse to the first declared one.
		var source = """
			using Aigamo.MatchGenerator;

			namespace Test;

			[GenerateMatch]
			public enum Visibility
			{
				None = 0,
				Private = 1,
				Internal = 2,
				Friend = Internal,
				Public = 3
			}
			""";

		var actual = RunGenerator(source);

		var expected = """
			// <auto-generated />
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;

			namespace Test;

			public static class VisibilityMatchExtensions
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static U Match<U>(
					this Visibility value,
					Func<U> None,
					Func<U> Private,
					Func<U> Internal,
					Func<U> Public
				)
				{
					return value switch
					{
						Visibility.None => None(),
						Visibility.Private => Private(),
						Visibility.Internal => Internal(),
						Visibility.Public => Public(),
						_ => throw new UnreachableException(),
					};
				}
			}

			""";

		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Reports_Diagnostic_For_Unsupported_External_Target()
	{
		// int is neither an enum nor a base type with derived types: nothing to match.
		var source = """
			using Aigamo.MatchGenerator;

			[assembly: GenerateMatchFor(typeof(int))]
			""";

		var result = Run(source);

		Assert.Contains(result.Diagnostics, d => d.Id == "AMG001");
		Assert.DoesNotContain(
			result.GeneratedTrees,
			t => t.FilePath.EndsWith("MatchExtensions.g.cs")
		);
	}

	[Fact]
	public void Generates_Match_Method_For_Record_Hierarchy()
	{
		var source = """
			using Aigamo.MatchGenerator;

			namespace Test;

			[GenerateMatch]
			abstract record MaritalStatus;

			sealed record Single : MaritalStatus;
			sealed record Married : MaritalStatus;
			sealed record Divorced : MaritalStatus;
			sealed record Widowed : MaritalStatus;
			""";

		var actual = RunGenerator(source);

		var expected = """
			// <auto-generated />
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;

			namespace Test;

			internal static class MaritalStatusMatchExtensions
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static U Match<U>(
					this MaritalStatus value,
					Func<Single, U> Single,
					Func<Married, U> Married,
					Func<Divorced, U> Divorced,
					Func<Widowed, U> Widowed
				)
				{
					return value switch
					{
						Single x => Single(x),
						Married x => Married(x),
						Divorced x => Divorced(x),
						Widowed x => Widowed(x),
						_ => throw new UnreachableException(),
					};
				}
			}

			""";

		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Generates_Match_Method_For_Record_Hierarchy_With_Custom_Parameter_Prefix()
	{
		var source = """
			using Aigamo.MatchGenerator;

			namespace Test;

			[GenerateMatch]
			abstract record MaritalStatus;

			sealed record Single : MaritalStatus;
			sealed record Married : MaritalStatus;
			sealed record Divorced : MaritalStatus;
			sealed record Widowed : MaritalStatus;
			""";

		var actual = RunGenerator(source, parameterPrefix: "on");

		var expected = """
			// <auto-generated />
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;

			namespace Test;

			internal static class MaritalStatusMatchExtensions
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static U Match<U>(
					this MaritalStatus value,
					Func<Single, U> onSingle,
					Func<Married, U> onMarried,
					Func<Divorced, U> onDivorced,
					Func<Widowed, U> onWidowed
				)
				{
					return value switch
					{
						Single x => onSingle(x),
						Married x => onMarried(x),
						Divorced x => onDivorced(x),
						Widowed x => onWidowed(x),
						_ => throw new UnreachableException(),
					};
				}
			}

			""";

		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Generates_Match_For_Record_Hierarchy_In_Global_Namespace()
	{
		var source = """
			using Aigamo.MatchGenerator;

			[GenerateMatch]
			abstract record MaritalStatus;

			sealed record Single : MaritalStatus;
			sealed record Married : MaritalStatus;
			sealed record Divorced : MaritalStatus;
			sealed record Widowed : MaritalStatus;
			""";

		var actual = RunGenerator(source);

		var expected = """
			// <auto-generated />
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;

			internal static class MaritalStatusMatchExtensions
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static U Match<U>(
					this MaritalStatus value,
					Func<Single, U> Single,
					Func<Married, U> Married,
					Func<Divorced, U> Divorced,
					Func<Widowed, U> Widowed
				)
				{
					return value switch
					{
						Single x => Single(x),
						Married x => Married(x),
						Divorced x => Divorced(x),
						Widowed x => Widowed(x),
						_ => throw new UnreachableException(),
					};
				}
			}

			""";

		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Generates_Match_For_Nested_Record_Hierarchy()
	{
		var source = """
			using Aigamo.MatchGenerator;

			namespace Test;

			[GenerateMatch]
			public abstract record MaritalStatus
			{
				private MaritalStatus() { }

				public sealed record Single : MaritalStatus;
				public sealed record Married : MaritalStatus;
				public sealed record Divorced : MaritalStatus;
				public sealed record Widowed : MaritalStatus;
			}
			""";

		var actual = RunGenerator(source);

		var expected = """
			// <auto-generated />
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;

			namespace Test;

			public static class MaritalStatusMatchExtensions
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static U Match<U>(
					this MaritalStatus value,
					Func<MaritalStatus.Single, U> Single,
					Func<MaritalStatus.Married, U> Married,
					Func<MaritalStatus.Divorced, U> Divorced,
					Func<MaritalStatus.Widowed, U> Widowed
				)
				{
					return value switch
					{
						MaritalStatus.Single x => Single(x),
						MaritalStatus.Married x => Married(x),
						MaritalStatus.Divorced x => Divorced(x),
						MaritalStatus.Widowed x => Widowed(x),
						_ => throw new UnreachableException(),
					};
				}
			}

			""";

		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Matches_Record_Accessibility()
	{
		var source = """
			using Aigamo.MatchGenerator;

			namespace Test;

			[GenerateMatch]
			internal abstract record MaritalStatus;

			internal sealed record Single : MaritalStatus;
			internal sealed record Married : MaritalStatus;
			internal sealed record Divorced : MaritalStatus;
			internal sealed record Widowed : MaritalStatus;
			""";

		var actual = RunGenerator(source);

		var expected = """
			// <auto-generated />
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;

			namespace Test;

			internal static class MaritalStatusMatchExtensions
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static U Match<U>(
					this MaritalStatus value,
					Func<Single, U> Single,
					Func<Married, U> Married,
					Func<Divorced, U> Divorced,
					Func<Widowed, U> Widowed
				)
				{
					return value switch
					{
						Single x => Single(x),
						Married x => Married(x),
						Divorced x => Divorced(x),
						Widowed x => Widowed(x),
						_ => throw new UnreachableException(),
					};
				}
			}

			""";

		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Respects_Containing_Type_Accessibility_For_Record_Hierarchy()
	{
		var source = """
			using Aigamo.MatchGenerator;

			namespace Test;

			internal class Container
			{
				[GenerateMatch]
				public abstract record MaritalStatus;

				public sealed record Single : MaritalStatus;
				public sealed record Married : MaritalStatus;
				public sealed record Divorced : MaritalStatus;
				public sealed record Widowed : MaritalStatus;
			}
			""";

		var actual = RunGenerator(source);

		var expected = """
			// <auto-generated />
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;

			namespace Test;

			internal static class MaritalStatusMatchExtensions
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static U Match<U>(
					this Container.MaritalStatus value,
					Func<Container.Single, U> Single,
					Func<Container.Married, U> Married,
					Func<Container.Divorced, U> Divorced,
					Func<Container.Widowed, U> Widowed
				)
				{
					return value switch
					{
						Container.Single x => Single(x),
						Container.Married x => Married(x),
						Container.Divorced x => Divorced(x),
						Container.Widowed x => Widowed(x),
						_ => throw new UnreachableException(),
					};
				}
			}

			""";

		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Generates_Match_For_Generic_Record_Hierarchy()
	{
		var source = """
			using Aigamo.MatchGenerator;

			namespace Test;

			[GenerateMatch]
			abstract record Option<T>
			{
				private Option() { }

				public sealed record Some(T Value) : Option<T>;
				public sealed record None : Option<T>;
			}
			""";

		var actual = RunGenerator(source);

		var expected = """
			// <auto-generated />
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;

			namespace Test;

			internal static class OptionMatchExtensions
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static U Match<T, U>(
					this Option<T> value,
					Func<Option<T>.Some, U> Some,
					Func<Option<T>.None, U> None
				)
				{
					return value switch
					{
						Option<T>.Some x => Some(x),
						Option<T>.None x => None(x),
						_ => throw new UnreachableException(),
					};
				}
			}

			""";

		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Generates_Match_For_Recursive_Generic_Record_Hierarchy()
	{
		var source = """
			using Aigamo.MatchGenerator;

			namespace Test;

			[GenerateMatch]
			abstract record List<T>
			{
				private List() { }

				public sealed record Empty : List<T>;
				public sealed record Cons(T Head, List<T> Tail) : List<T>;
			}
			""";

		var actual = RunGenerator(source);

		var expected = """
			// <auto-generated />
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;

			namespace Test;

			internal static class ListMatchExtensions
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static U Match<T, U>(
					this List<T> value,
					Func<List<T>.Empty, U> Empty,
					Func<List<T>.Cons, U> Cons
				)
				{
					return value switch
					{
						List<T>.Empty x => Empty(x),
						List<T>.Cons x => Cons(x),
						_ => throw new UnreachableException(),
					};
				}
			}

			""";

		Assert.Equal(expected, actual);
	}

	[Fact]
	public void Generates_Match_For_Generic_Record_Hierarchy_With_Multiple_Type_Parameters()
	{
		var source = """
			using Aigamo.MatchGenerator;

			namespace Test;

			[GenerateMatch]
			abstract record Either<L, R>
			{
				private Either() { }

				public sealed record Left(L Value) : Either<L, R>;
				public sealed record Right(R Value) : Either<L, R>;
			}
			""";

		var actual = RunGenerator(source);

		var expected = """
			// <auto-generated />
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;

			namespace Test;

			internal static class EitherMatchExtensions
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static U Match<L, R, U>(
					this Either<L, R> value,
					Func<Either<L, R>.Left, U> Left,
					Func<Either<L, R>.Right, U> Right
				)
				{
					return value switch
					{
						Either<L, R>.Left x => Left(x),
						Either<L, R>.Right x => Right(x),
						_ => throw new UnreachableException(),
					};
				}
			}

			""";

		Assert.Equal(expected, actual);
	}
}
